### ISSUE TITLE
Cross thread access in WPF

### ISSUE THREAD

**Issue by Plasmadog** [StephenCleary/CalculatedProperties#6]
Can you please clarify the point in the wiki about cross thread access. It says that WPF does cross thread marshaling, but is there a workaround or does that mean that this library just can't be used with WPF?

**Comment by StephenCleary** [comment]
This library works perfectly well with WPF. However, this library does not allow cross-thread access. WPF does allow cross-thread access for some kinds of properties. So you can use this library with WPF, but not in a cross-thread way.

Feel free to reopen if this isn't clear.

**Comment by Plasmadog** [comment]
Hi Stephen. Thanks for the quick response.
That's good to know, but we're having some issues in our WPF application. We have tried to create some Calculated properties sourced from an ObservableCollection that we get back as the Result of your [NotifyTaskCompletion](https://msdn.microsoft.com/magazine/dn605875) class, but we get a lot of exceptions due to cross-thread access. We're not explicitly creating any new threads; only Tasks to handle fetches from a DB. Can you suggest anything we can do to prevent the exceptions?

**Comment by StephenCleary** [comment]
Are you using `ConfigureAwait(false)`?

**Comment by Plasmadog** [comment]
No, the only await is the one in the NotifyTaskCompletion class, and that is exactly as you wrote it.

**Comment by StephenCleary** [comment]
Can you create a minimal code sample that reproduces the problem?

**Comment by ekalchev** [comment]
This is not issue in the library but in your code. I've seen this in our code base and it helped us resolve threading issue where we're setting viewmodel properties from worker thread. Use Dispatcher.VerifyAccess in your viewmodels to spot the problem earlier.

**Comment by Plasmadog** [comment]
[MinimalRepro.zip](https://github.com/StephenCleary/CalculatedProperties/files/2823618/MinimalRepro.zip)
Here is a code sample that throws exceptions on start.

**Comment by StephenCleary** [comment]
You're calling `Task<T>.Factory.StartNew`, which can use a thread pool thread. In this particular instance, it *is* using a thread pool thread. So, `GetItems` is running on a thread pool thread, and `TodoItem` is constructed on a thread pool thread. This is the cause of the cross-thread exception.

So, you'll need to fix the [async-over-sync antipattern](https://blogs.msdn.microsoft.com/pfxteam/2012/03/24/should-i-expose-asynchronous-wrappers-for-synchronous-methods/) in `TodoListService`. There's a few options.

The best option is to just go `async` all the way, particularly since this is dealing with I/O. However, based off your code comment "Our data normally comes from DB via an old version of NHibernate that does not provide async fetch methods", I'm assuming this isn't possible (or feasable) at this point.

Another option is to go synchronous all the way, and just drop `TodoListService.GetItemsAsync`. But I'm assuming that this would result in a degraded user experience, with the UI freezing too long.

So, we reach the option of using thread pool threads *only* to retrieve the domain model objects. The UI model objects (ViewModels, etc) *must* be constructed on the UI thread, so we need to switch back to the UI thread before doing that mapping. This would work:

```C#
public async Task<ObservableCollection<TodoItem>> GetItemsAsync()
{
    // fetch from repo/DB
    var obligations = await Task.Run(() => _repo.GetOutstandingObligations());

    // map domain model to UI model
    var todoItems = obligations.Select(obligation => new TodoItem(obligation));

    return new ObservableCollection<TodoItem>(todoItems);
}
```

(Side note: I've changed from the [dangerous `Task.Factory.StartNew`](https://blog.stephencleary.com/2013/08/startnew-is-dangerous.html) to the more reliable `Task.Run`; this change doesn't have anything to do with the cross-thread issue, but will save you pain the future)

So the approach above works, and that's fine except for the duplicated logic between `TodoListService.GetItems` and `TodoListService.GetItemsAsync`. That's ugly. If all your consumers can change from `GetItems` to `GetItemsAsync`, then take the code above and just drop `TodoListService.GetItems`.

But maybe you need to keep `TodoListService.GetItems` because other parts of your app still need it and aren't ready to switch to `async`. In that case, you can unify the logic in both of those methods by using the [bool argument hack](https://msdn.microsoft.com/en-us/magazine/mt238404.aspx):

```C#
private async Task<ObservableCollection<TodoItem>> GetItemsCoreAsync(bool sync)
{
    // fetch from repo/DB
    var obligations = sync ?
        _repo.GetOutstandingObligations() :
        await Task.Run(() => _repo.GetOutstandingObligations());

    // map domain model to UI model
    var todoItems = obligations.Select(obligation => new TodoItem(obligation));

    return new ObservableCollection<TodoItem>(todoItems);
}

public ObservableCollection<TodoItem> GetItems() => GetItemsCoreAsync(sync: true).GetAwaiter().GetResult();

public Task<ObservableCollection<TodoItem>> GetItemsAsync() => GetItemsCoreAsync(sync: false);
```

The semantics of the bool argument hack are that when `sync` is `true`, the "asynchronous" method behaves synchronously and returns an already-completed task (and thus it's safe to block on).

**Comment by Plasmadog** [comment]
Ah, OK. Thanks for the explanation, and for taking the time to investigate. I really appreciate it.
